/* isr.c
 * This file is modified form Bram's Kernel Development Tutorial
 * set up the Interrupt Service Routines, which handle excepitons generated by processor 
 */
 
#include <type.h>
#include <debug.h>
#include <idt.h>
#include <irq.h>
#include <fault.h>
#include <syscall.h>

extern void isr_unknown(); // see loader.asm

void isr_init() {
    fault_init();
    /* treat unkown interrupt as fault */
    int i;
    // Initialize the interrupt service routine as isr_unknown
    for (i = ISR_IRQ0; i < NIDT; i++) {
        idt_install(i,(uint32_t)isr_unknown, SEL_KCODE << 3, GATE_INT, IDT_PR|IDT_DPL_KERN);
    }

    irq_init();
}

void isr_stub(struct interrupt_frame *r) {
    if (r->int_no < ISR_IRQ0 || r->int_no == ISR_UNKNOWN) {
        fault_handler(r); // Default interrupt handling
    } else if (r->int_no < ISR_IRQ0 + 16) {
        irq_handler(r); //Specify interrupt handling
    } else if (r->int_no == ISR_SYSCALL) {
        syscall(); // system call
    } else {
        panic("isr_stub: wrong interrupt number", 0); // Interrupt number error
    }
}
